name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
    # Optionally configure to run only when specific files change
    # paths:
    #   - 'client/**'
    #   - 'server/**'
    #   - 'server.js'
    #   - 'package.json'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies and build client
      run: |
        npm install
        cd client
        npm install
        npm run build
        cd ..
        cd server
        npm install
        cd ..

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-name'           # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        
    - name: Set up environment variables
      uses: azure/appservice-settings@v1
      with:
        app-name: 'your-app-name'           # Replace with your app name
        app-settings-json: |
          [
            {
              "name": "MONGODB_URI",
              "value": "${{ secrets.MONGODB_URI }}",
              "slotSetting": false
            },
            {
              "name": "NODE_ENV",
              "value": "production",
              "slotSetting": false
            },
            {
              "name": "PORT",
              "value": "8080",
              "slotSetting": false
            }
          ]
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
